# Generated by Django 5.2.5 on 2025-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_comment_like_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
